FROM php:5.6-apache

WORKDIR /etc/apache2/mods-enabled

RUN ln -s ../mods-available/rewrite.load rewrite.load

COPY HelloWorld/ /var/www/html/

WORKDIR /

RUN sed -i 's/KeepAlive On/KeepAlive Off/g' /etc/apache2/apache2.conf

EXPOSE 80/tcp
