FROM php:5.6-apache

COPY HelloWorld/ /var/www/html/

RUN mkdir -p /mnt/images
RUN chown www-data: /mnt/images
RUN sed -i 's/KeepAlive On/KeepAlive Off/g' /etc/apache2/apache2.conf
RUN ln -s /etc/apache2/mods-available/rewrite.load /etc/apache2/mods-enabled/rewrite.load

EXPOSE 80/tcp
